[package]
name = "laches_mon"
version = "0.1.0"
edition = "2021"
authors = ["Ibrahim Hisham <ibrahim.hisham@proton.me>"]
license = "MIT"

[dependencies]
laches = { path = "../laches" }

clap.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = "3.8"
