[package]
name = "laches_mon"
authors = ["Ibrahim Hisham <ibrahim.hisham@proton.me>"]
version = "0.1.0"
edition = "2021"

[dependencies]
laches = { path = "../laches" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile = "3.8"
